[package]
name = "sgf-render"
version = "0.1.0"
authors = ["Julian Andrews <jandrews@fusionbox.com>"]
edition = "2018"
include = ["data/Roboto-bold.ttf"]

[features]
default = ["png"]
png = ["resvg", "usvg"]

[dependencies]
sgf-parse = "^2.0.0"
svg = "^0.8.0"

resvg = { version = "^0.11.0", features = ["text"], optional = true }
usvg = { version = "^0.11.0", optional = true }
