[package]
name = "sgf-render"
version = "1.3.3"
authors = ["Julian Andrews <jandrews271@gmail.com>"]
edition = "2018"
license = "MIT"
keywords = ["baduk", "sgf", "go", "svg", "png"]
repository = "https://github.com/julianandrews/sgf-render/"
readme = "README.md"
description = "A renderer for SGF diagrams."
categories = ["command-line-utilities", "multimedia::images", "rendering", "visualization"]

[features]
default = ["png"]
png = ["resvg", "usvg", "tiny-skia"]

[dependencies]
getopts = "0.2.21"
sgf-parse = "3.1.1"
svg = "0.9.2"

resvg = { version = "0.14.1", features = ["text"], optional = true }
usvg = { version = "0.14.1", optional = true }
tiny-skia = { version = "0.5.0", optional = true }
